### ISSUE TITLE
Types and functions for RLC circuits

### ISSUE THREAD

**Issue by NewLunarFire** [antoineMoPa/livecalc.xyz#125]
We could create data types that represent Resistors, Capacitors and Inductors, make calculations on them like finding resonant and cutoff frequencies, gain and phase shifts or time constants and graph plots like time response or Fourier transforms.

Basically all the EE stuff from the last 2 semesters.

**Comment by antoineMoPa** [comment]
Just for a project follow-up:

I am not targeting electrical engineers specifically anymore (That's why I renamed the project from eecalc to livecalc [but this may change soon since LiveCalc is already used by a mac calculator]).

The plan is now to build a general purpose calculator and pack in as many features as possible while keeping the app fast. On the marketing side, I'd like to target education. The "pro" accounts will give people access to more server resources (more users online at the same time, server-side math software, etc.) (But it will always stay free and open source and downloadable).

That being said, let's go back to your issue:

* data types: I think a lot are already in math.js (try `3 Ohm`, henry, watt, amperes, etc.)
* Specific calculations on them: I think that would be too specific to EE. However, this could be done in separate demo sheets that we would reference in a page. (Example: a sheet with an example of a voltage divider. People could copy that sheet and do their math)
* Since I don't want to target EE too much, we would also have to create examples for other domains like high school physics.
* Gain and Phase shift (+ Bode plots) : that is specific, but I would still consider it a great add to livecalc so I recommend we do it.
* Fourier transform: I agree

However, we can wait to support octave as a backend, since it would solve many of these problems (transfer function, bode plots, etc.).

**Comment by antoineMoPa** [comment]
Closing because lack of activity

**Comment by NewLunarFire** [comment]
The issue was pretty much resolved with your feedback. Thanks.
